services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webserver
      - was
    networks:
      - nginx-webserver
      - nginx-was
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proxy_default.conf:/etc/nginx/conf.d/proxy_default.conf
      - /etc/letsencrypt/live/nginx.millons-io.store/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/nginx.millons-io.store/privkey.pem:/etc/nginx/certs/privkey.pem:ro

  webserver:
    image: seonghooncho/node-server:2.0
    container_name: webserver
    expose:
      - "3000"
    networks:
      - nginx-webserver

  was:
    image: seonghooncho/millions-was:1.0
    # scaling 을 위해서 container name 지정 X
    expose:
      - "8080"
    networks:
      - nginx-was
      - was-db
    depends_on:
      - mysql
      - mongo
      - redis

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yourpw
    expose:
      - "3306"
    networks:
      - was-db
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:latest
    container_name: mongo
    expose:
      - "27017"
    networks:
      - was-db
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    networks:
      - was-db


networks:
  nginx-webserver:
  nginx-was:
  was-db:

volumes:
  mysql_data:
  mongo_data: