spring:
  config:
    import: "optional:aws-parameterstore:/millions/backend/"

  cloud:
    aws:
      parameterstore:
        enabled: true
      region:
        static: ap-northeast-2
      credentials:
        instance-profile: true

  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  data:
    mongodb:
      uri: ${MONGO_URL}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}

  profiles:
    active: dev


auth:
  token:
    hmacSecretBase64: ${JWT_SECRET_KEY} #jwt 서명키

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace   # Hibernate 6 (파라미터 바인딩 로그)

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ap-northeast-2
  s3:
    bucket: ${AWS_S3_BUCKET_NAME}
  cloudfront:
    domain: ${AWS_CLOUDFRONT_DOMAIN}
    key-pair-id: ${AWS_CLOUDFRONT_KEY_PAIR_ID}
    private-key: ${AWS_CLOUDFRONT_PRIVATE_KEY}


app:
  cors:
    allowed-origin-patterns:
      - "http://localhost:*"
      # 배포서버
      - "http://3.35.185.103:3000"
      - "http://millons-io.store"
      - "http://millons-io.store:3000"
      - "https://nginx.millons-io.store"
      - "https://millons-io.store"
    cred-paths:
      - "/api/auth"
      - "/api/images/signed-cookie"

  security:
    public-apis:
      - "/api/auth"
      - "/api/auth/signup/email-verification-code"
      - "/api/auth/signup/email-verification-code/retry"
      - "/api/auth/recover/email-verification-code"
      - "/api/members/recover"
    jwt-exclude-paths:
      - "/api/auth"
      - "/api/auth/signup/**"
      - "/api/auth/recover/**"


management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    base-path: /api
  metrics:
    binders:
      processor: false

