spring:
  datasource:
    url: ${/millions/backend/DB_HOST}
    username: ${/millions/backend/DB_USERNAME}
    password: ${/millions/backend/DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  data:
    mongodb:
      uri: ${/millions/backend/MONGO_URL}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${/millions/backend/MAIL_USER}
    password: ${/millions/backend/MAIL_PASSWORD}

  profiles:
    active: dev


auth:
  token:
    hmacSecretBase64: ${/millions/backend/JWT_SECRET_KEY} # jwt 서명키

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace   # Hibernate 6 (파라미터 바인딩 로그)

aws:
  credentials:
    access-key: ${/millions/backend/AWS_ACCESS_KEY}
    secret-key: ${/millions/backend/AWS_SECRET_KEY}
  region: ap-northeast-2
  s3:
    bucket: ${/millions/backend/S3_BUCKET}   # ← SSM에 새로 하나 만드는 걸 추천
  cloudfront:
    domain: ${/millions/backend/CLOUDFRONT_DOMAIN}
    key-pair-id: ${/millions/backend/CLOUDFRONT_KEYPAIR}
    private-key: ${/millions/backend/CLOUDFRONT_PRIVATE_KEY}


app:
  cors:
    allowed-origin-patterns:
      - "http://localhost:*"
      # 배포서버
      - "http://3.35.185.103:3000"
      - "http://millons-io.store"
      - "http://millons-io.store:3000"
    cred-paths:
      - "/api/auth"
      - "/api/images/signed-cookie"

  security:
    public-apis:
      - "/api/auth"
      - "/api/auth/signup/email-verification-code"
      - "/api/auth/signup/email-verification-code/retry"
      - "/api/auth/recover/email-verification-code"
      - "/api/members/recover"
    jwt-exclude-paths:
      - "/api/auth"
      - "/api/auth/signup/**"
      - "/api/auth/recover/**"


management:
  endpoints:
    web:
      exposure:
        include: health
